-- Run with the SQL administrator in a test transaction. All changes roll back.
begin;
select set_config('qa.profe',(select user_id::text from public.gf_profiles where role='profe' limit 1),true);
select set_config('qa.admin',(select user_id::text from public.gf_profiles where role='admin' and is_master limit 1),true);
select set_config('qa.client',(select user_id::text from public.gf_profiles where role='cliente' limit 1),true);
set local role authenticated;
do $$
declare v_count int; v_id uuid; v_denied boolean; v_state jsonb;
begin
 perform set_config('request.jwt.claim.sub',current_setting('qa.profe'),true);
 v_state:=public.gf_get_gym_state();
 if jsonb_array_length(v_state->'people')<>0 then raise exception 'Restricted state leaked'; end if;
 v_denied:=false;
 begin perform public.gf_list_routine_clients(); exception when raise_exception then v_denied:=true; end;
 if not v_denied then raise exception 'Student RPC should deny'; end if;
 v_denied:=false;
 begin perform public.gf_set_professor_permission(auth.uid(),'canViewStudents',true); exception when raise_exception then v_denied:=true; end;
 if not v_denied then raise exception 'Self grant allowed'; end if;
 v_denied:=false;
 begin insert into public.gf_exercises(name,created_by) values('QA rollback',auth.uid()); exception when insufficient_privilege then v_denied:=true; end;
 if not v_denied then raise exception 'Create without grant allowed'; end if;
 perform set_config('request.jwt.claim.sub',current_setting('qa.admin'),true);
 perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canViewStudents',true);
 perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canCreateExercises',true);
 perform set_config('request.jwt.claim.sub',current_setting('qa.profe'),true);
 perform public.gf_list_routine_clients();
 insert into public.gf_exercises(name,created_by) values('QA rollback',auth.uid()) returning id into v_id;
 update public.gf_exercises set notes='denied' where id=v_id;
 get diagnostics v_count=row_count;
 if v_count<>0 then raise exception 'Edit without grant allowed'; end if;
 delete from public.gf_exercises where id=v_id;
 get diagnostics v_count=row_count;
 if v_count<>0 then raise exception 'Delete without grant allowed'; end if;
 perform set_config('request.jwt.claim.sub',current_setting('qa.admin'),true);
 perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canEditExercises',true);
 perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canDeleteExercises',true);
 perform set_config('request.jwt.claim.sub',current_setting('qa.profe'),true);
 update public.gf_exercises set notes='allowed' where id=v_id;
 get diagnostics v_count=row_count;
 if v_count<>1 then raise exception 'Granted edit failed'; end if;
 update public.gf_exercises set notes='forbidden' where is_system;
 get diagnostics v_count=row_count;
 if v_count<>0 then raise exception 'System edit allowed'; end if;
 delete from public.gf_exercises where id=v_id;
 get diagnostics v_count=row_count;
 if v_count<>1 then raise exception 'Granted delete failed'; end if;
 perform set_config('request.jwt.claim.sub',current_setting('qa.admin'),true);
 perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canViewStudents',false);
 perform set_config('request.jwt.claim.sub',current_setting('qa.profe'),true);
 v_denied:=false;
 begin perform public.gf_list_routine_clients(); exception when raise_exception then v_denied:=true; end;
 if not v_denied then raise exception 'Revocation failed'; end if;
 perform set_config('request.jwt.claim.sub',current_setting('qa.client'),true);
 v_denied:=false;
 begin perform public.gf_set_professor_permission(current_setting('qa.profe')::uuid,'canCreateExercises',true); exception when raise_exception then v_denied:=true; end;
 if not v_denied then raise exception 'Client grant allowed'; end if;
end; $$;
rollback;
